# Generated by Django 4.2.13 on 2026-03-20 12:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(max_length=255, verbose_name="ファイル名")),
                ("total_rows", models.IntegerField(default=0, verbose_name="総行数")),
                ("ok_count", models.IntegerField(default=0, verbose_name="成功件数")),
                ("skip_count", models.IntegerField(default=0, verbose_name="スキップ件数")),
                ("error_count", models.IntegerField(default=0, verbose_name="エラー件数")),
                (
                    "executed_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="実行日時"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="import_runs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="実行者",
                    ),
                ),
            ],
            options={
                "verbose_name": "CSVインポート記録",
                "verbose_name_plural": "CSVインポート記録",
                "ordering": ["-executed_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="日付")),
                (
                    "clock_in",
                    models.TimeField(blank=True, null=True, verbose_name="出勤時刻"),
                ),
                (
                    "clock_out",
                    models.TimeField(blank=True, null=True, verbose_name="退勤時刻"),
                ),
                ("break_min", models.IntegerField(default=60, verbose_name="休憩時間（分）")),
                ("note", models.TextField(blank=True, default="", verbose_name="備考")),
                (
                    "status",
                    models.CharField(
                        choices=[("DRAFT", "一時保存"), ("SUBMITTED", "提出済み")],
                        default="DRAFT",
                        max_length=16,
                        verbose_name="ステータス",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workdays",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="社員",
                    ),
                ),
            ],
            options={
                "verbose_name": "勤怠レコード",
                "verbose_name_plural": "勤怠レコード",
                "ordering": ["-date"],
                "unique_together": {("user", "date")},
            },
        ),
        migrations.CreateModel(
            name="ValidationError",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("row_number", models.IntegerField(verbose_name="行番号")),
                ("error_code", models.CharField(max_length=32, verbose_name="エラーコード")),
                ("message", models.TextField(verbose_name="エラーメッセージ")),
                (
                    "import_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="validation_errors",
                        to="attendance.importrun",
                        verbose_name="インポート記録",
                    ),
                ),
            ],
            options={
                "verbose_name": "バリデーションエラー",
                "verbose_name_plural": "バリデーションエラー",
                "ordering": ["row_number"],
            },
        ),
        migrations.CreateModel(
            name="ChangeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field_name", models.CharField(max_length=32, verbose_name="フィールド名")),
                (
                    "before_value",
                    models.TextField(blank=True, default="", verbose_name="変更前"),
                ),
                (
                    "after_value",
                    models.TextField(blank=True, default="", verbose_name="変更後"),
                ),
                (
                    "changed_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="変更日時"),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="changelogs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="変更者",
                    ),
                ),
                (
                    "workday",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="changelogs",
                        to="attendance.workday",
                        verbose_name="勤怠レコード",
                    ),
                ),
            ],
            options={
                "verbose_name": "変更ログ",
                "verbose_name_plural": "変更ログ",
                "ordering": ["-changed_at"],
            },
        ),
    ]
